### ISSUE TITLE
Change color of recommendations, noob, and bounty messages

### ISSUE THREAD

**Issue by Silverlight42** [cyberarm/mobius#12]
Maybe change it to light orange or light gold? Something to distinguish them from normal chat messages.

**Comment by cyberarm** [comment]
Fixed in 5352e8417a5f29a038ce3892e4619d88c1f29e67. Bounty, noob/recs broadcast messages are now MOBIUS brown/orange.

Rec'd and noob'd broadcast messages match configured team color of target player.
