### ISSUE TITLE
Bounty plugin

### ISSUE THREAD

**Issue by Silverlight42** [cyberarm/mobius#4]
Placeholder issue

This might be doable in the future when we can access the player's current credits.

**Comment by cyberarm** [comment]
We can get the players credits/money from the `pinfo` command, and can take credits from players by providing a negative number to the `credits` command.

**Comment by Silverlight42** [comment]
Are you sure? The last time I tried getting the player credits I couldn't get the info via pinfo.

**Comment by cyberarm** [comment]
Hmm, well it seems to work nowadays.
![bitmap-croppy](https://user-images.githubusercontent.com/581879/222932019-4896fc6d-59ff-4010-b177-4079b91b9f3f.png)

**Comment by cyberarm** [comment]
Done
